version: '3.9'

services:
  laravel:
    image: 'laravel11'
    ports:
      - '9000:8000'
    volumes:
      - ./:/app
    command: php artisan serve --host=0.0.0.0
    links:
      - 'postgres'

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=laravelTest
      - POSTGRES_PASSWORD=laravelTest
      - POSTGRES_DB=laravelTestdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
